version: '3'
services:
  back:
    image: sikgates/newimage:latest  # Docker Hub에서 가져오기
    ports:
      - "5001:5001"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - TZ=Etc/UTC
      - MONGO_PW=PAD0MzMGKxsDGwsR
      - REDIS_HOST=redis-14438.c281.us-east-1-2.ec2.redns.redis-cloud.com
      - REDIS_PORT=14438
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=AoWvAXv3JTPRBrgwxRX58G9AVxFhQzpj
      - GOOGLE_APPLICATION_CREDENTIALS=/back/campuscoffee-83cbf-74f467acc07d.json
    depends_on:
      - redis
      - rabbitmq
    command: node app.js
    deploy:  # 리소스 설정 추가
      resources:
        limits:
          cpus: "1.0"  # 최대 1 CPU 코어 사용
          memory: "1g"  # 최대 1GB 메모리 사용
        reservations:
          cpus: "0.5"  # 최소 0.5 CPU 코어 예약
          memory: "512m"  # 최소 512MB 메모리 예약
    networks:
      - app_network

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:4.0.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - TZ=Etc/UTC
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    deploy:  # 리소스 설정 추가
      resources:
        limits:
          cpus: "0.5"  # 최대 0.5 CPU 코어 사용
          memory: "512m"  # 최대 512MB 메모리 사용
        reservations:
          cpus: "0.25"  # 최소 0.25 CPU 코어 예약
          memory: "256m"  # 최소 256MB 메모리 예약
    networks:
      - app_network

  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Etc/UTC
    command: ["redis-server", "--requirepass", "yourpassword", "--notify-keyspace-events", "KEA"]
    deploy:  # 리소스 설정 추가
      resources:
        limits:
          cpus: "0.5"  # 최대 0.5 CPU 코어 사용
          memory: "512m"  # 최대 512MB 메모리 사용
        reservations:
          cpus: "0.25"  # 최소 0.25 CPU 코어 예약
          memory: "256m"  # 최소 256MB 메모리 예약
    networks:
      - app_network

networks:
  app_network:
    driver: bridge