version: '3'
services:
  back:
    image: sikgates/eighteen-back:latest  # Docker Hub에서 가져오기
    ports:
      - "5001:5001"
    volumes:
      - ./back:/app
      - /app/node_modules
     # - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGO_PW=PAD0MzMGKxsDGwsR
      - REDIS_HOST=redis-14438.c281.us-east-1-2.ec2.redns.redis-cloud.com
      - REDIS_PORT=14438
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=AoWvAXv3JTPRBrgwxRX58G9AVxFhQzpj
     #- TZ=Asia/Seoul
    depends_on:
      - redis
      - rabbitmq
    command: node app.js
    networks:
      - app_network

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:4.0.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
     # - /etc/localtime:/etc/localtime:ro
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    #  - TZ=Asia/Seoul
    networks:
      - app_network

  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
     # - /etc/localtime:/etc/localtime:ro
    environment:
    #  - TZ=Asia/Seoul
    command: ["redis-server", "--requirepass", "yourpassword", "--notify-keyspace-events", "KEA"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge