version: '3.8'
services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Express 서버 포트
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - MONGO_PW=PAD0MzMGKxsDGwsR
      - REDIS_HOST=redis-14438.c281.us-east-1-2.ec2.redns.redis-cloud.com
      - REDIS_PORT=14438
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=AoWvAXv3JTPRBrgwxRX58G9AVxFhQzpj
      #- RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq # RabbitMQ 컨테이너가 먼저 실행되도록 설정
    command: node app.js
    networks:
      - app_network

  rabbitmq: # RabbitMQ 서비스
    image: rabbitmq:3-management # RabbitMQ 관리 UI 포함 이미지
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ AMQP 포트
      - "15672:15672" # RabbitMQ 관리 UI 포트
    environment:
      RABBITMQ_DEFAULT_USER: guest # RabbitMQ 기본 사용자 이름
      RABBITMQ_DEFAULT_PASS: guest # RabbitMQ 기본 비밀번호
    networks:
      - app_network


networks:
  app_network:
    driver: bridge