name: Build and Push Docker Image to Docker Hub and Deploy to EC2

on:
  push:
    branches:
      - sub  # sub 브랜치에 푸시 시 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Docker 이미지 빌드
      - name: Build Docker Image
        run: |
          docker build -t sikgates/eighteen-back:latest ./back

      # 4. Docker Hub에 푸시
      - name: Push Docker Image
        run: |
          docker push sikgates/eighteen-back:latest

  deploy:
  runs-on: ubuntu-latest
  needs: build-and-push

  steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.3  # 안정 버전 사용
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        debug: true  # 디버깅 활성화
        script: |
          # 디렉토리 이동 (파일 위치 확인 필요)
          cd /home/ubuntu/eighteen || { echo "Directory not found"; exit 1; }          # 기존 컨테이너 및 네트워크 정리
          sudo docker-compose down || { echo "docker-compose down failed"; exit 1; }
          # 이미지 pull
          sudo docker pull sikgates/eighteen-back:latest || { echo "pull eighteen-back failed"; exit 1; }
          sudo docker pull heidiks/rabbitmq-delayed-message-exchange:4.0.2-management || { echo "pull rabbitmq failed"; exit 1; }
          sudo docker pull redis:7.4.2 || { echo "pull redis failed"; exit 1; }
          # 컨테이너 재실행
          sudo docker-compose up -d || { echo "docker-compose up failed"; exit 1; }
          echo "Deployment completed successfully."